version: "3.8"

services:
  mc-server:
    image: minecraft-modpack
    container_name: mc-modpack
    environment:
      - MEMORY=6G
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 6G
